### ISSUE TITLE
Developing on Windows

### ISSUE THREAD

**Issue by leun4m** [leun4m/symbsearch#46]
Still trying to figure out how to develop under windows.

When I compile it with Visual Studio I get the following error message:
```
System.DllNotFoundException was unhandled
Message=Unable to load DLL 'libgtk-win32-2.0-0.dll':
The specified procedure could not be found.
(Exception from HRESULT: 0x8007007F)
```

*I have GTK# and Mono installed.*

**Comment by oliver-krebs** [comment]
I assume you have checked the PATH?
Do you have the dll on your system?
Which versions are you using?

You could also try to build MonoDevelop and then open and compile the project there:
http://www.monodevelop.com/developers/building-monodevelop/#windows
However, probably this won't solve the problem.

**Comment by leun4m** [comment]
Yes, I did check the PATH and I have the dll.
I am using
- Microsoft Visual Studio Community 2017 - Version 15.5.3
- Mono Compiler 5.4.1 (32-bit)

I tried now to embed the Mono into Visual Studio following [this](https://nbevans.wordpress.com/2013/02/13/targeting-mono-in-visual-studio-2012/) guide. It seemed to be quite succesfull, however the problem is now he doesn't recognizes the `System` namespace – I get now error highlighting on the the first three lines

```cs
using System;
using System.Reflection;
using System.Collections.Generic;
```
marked as:

> The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	

And that are not the only errors appearing...

**Comment by leun4m** [comment]
I tried
```
$ xbuild SymbSearch.sln
```

and get:

```
Build succeeded.
         0 Warning(s)
         0 Error(s)
```

and it really creates a *result* in the bin/Debug directory, containing:
- atk-sharp.dll
- atk-sharp.pdb
- gdk-sharp.dll
- gdk-sharp.pdb
- glade-sharp.dll
- glade-sharp.pdb
- glib-sharp.dll
- glib-sharp.pdb
- gtk-sharp.dll
- Mono.CSharp.dll
- Mono.Posix.dll
- Newtonsoft.Json.dll
- Newtonsoft.Json.xml
- pango-sharp.dll
- pango-sharp.pdb
- SymbSearch.exe
- SymbSearch.exe.config
- SymbSearch.pdb

Unfortunately SymbSearch.exe is not going to start. It doesn't repeat with an error message or something but after a few seconds it just dissapears from the processes shown by the Task-Manager.

**Comment by leun4m** [comment]
I tried to use `msbuild` instead now since the following line:
> xbuild tool is deprecated and will be removed in future updates, use msbuild instead 

And I get the following error message:

> C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB6004: The specified task executable location "\\csc.exe" is invalid.

**Comment by oliver-krebs** [comment]
Okay, I could build it with Visual Studio and start it on Windows!
You need to change the project properties, so the application is started with mono:
```
Start action: start external program = <Installation Path> mono.exe
Start options: command line arguments = SymbSearch.exe
working directory = ‘build location of the assembly’ (bin/Debug)
```

**Comment by leun4m** [comment]
Wow, that finally made it :)
Thanks a lot.

(The only further thing I needed to do was to copy **categories.json** and **symbols.json** into `bin/Debug`)
