### ISSUE TITLE
Search: Upper and Lowercase

### ISSUE THREAD

**Issue by leun4m** [leun4m/symbsearch#7]
The search should mention if the word is upper or lowercase.

For example:
"Gamma" → Γ
"gamma" → γ

**Comment by leun4m** [comment]
I don't think this is a good idea anymore.

**Comment by oliver-krebs** [comment]
This is already done with a Case Sensitive option:
https://github.com/leun4m/symbsearch/commit/41b130f869fbb1cf1f6c7a935f97230feec8ac2c
